from selenium.webdriver.common.by import By
from utilities.BaseClass import BaseClass


class AdminInspectionPage(BaseClass):
    projects = (By.XPATH, "(//span[contains(text(),'Projects')])[1]")
    inspection = (By.XPATH, "(//button[@title='Inspection'])[1]")
    folderOne = (By.XPATH, "//h4[contains(text(),'1.folder_one')]")
    subFolderOne = (By.XPATH, "//h4[contains(text(),'1.One')] ")
    folderTwo = (By.XPATH, "//h4[contains(text(),'2.Folder_two')]")
    subFolderTwo = (By.XPATH, "//h4[contains(text(),'1.One')]")
    folderThree = (By.XPATH, "//h4[contains(text(),'3.Folder_three')]")
    subFolderThree = (By.XPATH, "//h4[contains(text(),'1.One')]")
    selectSix = (By.XPATH, "(//button[@class='vs-con-dropdown parent-dropdown'])[6]")
    mapSix = (By.XPATH, "(//div[@class='pin cursor-grab'])[6]")
    uploadImage = (By.XPATH, "//div[@class='image-card text-center position-relative']")
    folderSix = (By.XPATH, "//h4[@title='Folder_six']")
    dragSix = (By.XPATH, "(//div[@class='text-white yellow-pin'])[6]")
    dragSubFolder = (By.XPATH, "//div[@class='text-white yellow-pin']")
    saveData = (By.XPATH, "//button[@class='vs-component vs-button vs-component vs-button vs-button-warning vs-button-filled vs-button-warning vs-button-filled']")

    def __init__(self, driver):
        self.driver = driver

    def adminInspection(self, getData):
        self.elementClick(self.driver.find_element(*AdminInspectionPage.projects))
        self.elementClick(self.driver.find_element(*AdminInspectionPage.inspection))
        self.webScroll(getData["Scrolling"])
        self.section(getData["SectionNameSix"])
        self.sleep(2)
        self.webScroll(getData["Scrolling"])
        self.elementClickByJS(self.driver.find_element(*AdminInspectionPage.selectSix))
        self.createMap()
        self.elementClickByJS(self.driver.find_element(*AdminInspectionPage.mapSix))
        self.elementClick(self.driver.find_element(*AdminInspectionPage.mapSix))
        self.dragTheLocationSix(self.driver.find_element(*AdminInspectionPage.dragSix))
        self.elementClick(self.driver.find_element(*AdminInspectionPage.folderSix))
        self.subFolderClick(getData["SubFolderNameSix"])
        self.subFolderMapping()
        self.dragTheLocationSubFolder(self.driver.find_element(*AdminInspectionPage.dragSubFolder))
        self.webScroll(getData["Scrolling"])
        self.sleep(2)
        self.elementClickByJS(self.driver.find_element(*AdminInspectionPage.folderOne))
        self.elementClickByJS(self.driver.find_element(*AdminInspectionPage.subFolderOne))

        self.uploadPhotos("C:\\Users\\ALAGU SUNDARI\\PycharmProjects\\IQ-CRM_Admin\\TestData\\ImagesFolder\\20240204 (282)_1024x768.jpg")
        self.uploadPhotos("C:\\Users\\ALAGU SUNDARI\\PycharmProjects\\IQ-CRM_Admin\\TestData\ImagesFolder\\20240204 (283)_1024x768.jpg")
        self.uploadPhotos("C:\\Users\\ALAGU SUNDARI\\PycharmProjects\\IQ-CRM_Admin\\TestData\ImagesFolder\\20240204 (284)_1024x768.jpg")
        self.closeFolder()
        self.webScroll(getData["Scrolling"])
        self.sleep(2)
        self.elementClickByJS(self.driver.find_element(*AdminInspectionPage.folderTwo))
        self.elementClick(self.driver.find_element(*AdminInspectionPage.subFolderTwo))
        self.uploadPhotos("C:\\Users\\ALAGU SUNDARI\\PycharmProjects\\IQ-CRM_Admin\\TestData\\ImagesFolder\\20240204 (282)_1024x768.jpg")
        self.uploadPhotos("C:\\Users\\ALAGU SUNDARI\\PycharmProjects\\IQ-CRM_Admin\\TestData\ImagesFolder\\20240204 (283)_1024x768.jpg")
        self.uploadPhotos("C:\\Users\\ALAGU SUNDARI\\PycharmProjects\\IQ-CRM_Admin\\TestData\ImagesFolder\\20240204 (284)_1024x768.jpg")
        self.closeFolder()
        self.webScroll(getData["Scrolling"])
        self.sleep(2)
        self.elementClickByJS(self.driver.find_element(*AdminInspectionPage.folderThree))
        self.elementClick(self.driver.find_element(*AdminInspectionPage.subFolderThree))

        self.uploadPhotos("C:\\Users\\ALAGU SUNDARI\\PycharmProjects\\IQ-CRM_Admin\\TestData\\ImagesFolder\\20240204 (282)_1024x768.jpg")
        self.uploadPhotos("C:\\Users\\ALAGU SUNDARI\\PycharmProjects\\IQ-CRM_Admin\\TestData\ImagesFolder\\20240204 (283)_1024x768.jpg")
        self.uploadPhotos("C:\\Users\\ALAGU SUNDARI\\PycharmProjects\\IQ-CRM_Admin\\TestData\ImagesFolder\\20240204 (284)_1024x768.jpg")
        self.closeFolder()
        self.sleep(2)
        self.webScroll(getData["Scrolling"])
        self.elementClick(self.driver.find_element(*AdminInspectionPage.saveData))
