from selenium.webdriver.common.by import By
from utilities.BaseClass import BaseClass
import autoit


class InspectionPage(BaseClass):
    service = (By.XPATH, "//div[@name ='service']")
    scrollToConsultantService = (By.XPATH, "//div[@class ='vx-card']/div/div/h4[text()='Select Consultant and Service']")
    executiveSummaryClick = (By.XPATH, "(//span[@class='icon-header vs-collapse-item--icon-header'])[1]")
    frameClick = (By.XPATH, "//iframe[@class ='cke_wysiwyg_frame cke_reset']")

    clearExecutiveSummary = (By.XPATH, "//body[@class ='cke_editable cke_editable_themed cke_contents_ltr cke_show_borders']")
    executiveSummarySaveData = (By.XPATH, "(//span[contains(text(),'Save data')])[1]")
    vesselAssessmentClick = (By.XPATH, "(//i[@class ='vs-icon notranslate icon-scale feather icon-arrow-down null'])[2]")
    selectVesselAssessment = (By.XPATH, "(//span[@class ='vs-radio'])[8]")
    generalInformationClick = (By.XPATH, "(//i[@class ='vs-icon notranslate icon-scale feather icon-arrow-down null'])[3]")
    vesselAssessmentSaveData = (By.XPATH, "(//span[contains(text(),'Save data')])[2]")
    enterGeneralInformationOne = (By.XPATH, "(//div[@class ='mb-4 general-details-table']/table/tbody/tr)[2]/td[@class ='w-full text-dark']")
    enterGeneralInformationTwo = (By.XPATH, "(//div[@class ='mb-4 general-details-table']/table/tbody/tr)[4]/td[@class='w-full text-dark']")
    generalInformationSaveData = (By.XPATH, "(//span[contains(text(),'Save data')])[3]")
    generalImageClick = (By.XPATH, "(//i[@class ='vs-icon notranslate icon-scale feather icon-arrow-down null'])[4]")
    selectGeneralImage = (By.XPATH, "//*[local-name()='svg' and @class='feather feather-plus ']")
    chooseFile = (By.XPATH, "//div/input[@name ='url']")
    generalImageSaveData = (By.XPATH, "//button[@id='save-answer']")
    description = (By.XPATH, "//textarea[@name ='role_description']")
    section = (By.XPATH, "//div[@name ='section']")
    subSection = (By.XPATH, "//div[@name ='sub_section']//descendant::input")
    qualificationOfOfficersClick = (By.XPATH, "(//i[@class ='vs-icon notranslate icon-scale feather icon-arrow-down null'])[5]")
    masterDetailsOne = (By.XPATH, "(((//div[@class ='officers-details mb-4']/table/tbody)[1]/tr)[2]/td)[2]")
    masterDetailsTwo = (By.XPATH, "(((//div[@class ='officers-details mb-4']/table/tbody)[1]/tr)[2]/td)[3]")
    masterDetailsThree = (By.XPATH, "(((//div[@class ='officers-details mb-4']/table/tbody)[1]/tr)[2]/td)[4]")
    chiefOfficerDetailsOne = (By.XPATH, "(((//div[@class ='officers-details mb-4']/table/tbody)[1]/tr)[3]/td)[2]")
    chiefOfficerDetailsTwo = (By.XPATH, "(((//div[@class ='officers-details mb-4']/table/tbody)[1]/tr)[3]/td)[3]")
    chiefOfficerDetailsThree = (By.XPATH, "(((//div[@class ='officers-details mb-4']/table/tbody)[1]/tr)[3]/td)[4]")
    secondOfficerDetailsOne = (By.XPATH, "(((//div[@class ='officers-details mb-4']/table/tbody)[1]/tr)[4]/td)[2]")
    secondOfficerDetailsTwo = (By.XPATH, "(((//div[@class ='officers-details mb-4']/table/tbody)[1]/tr)[4]/td)[3]")
    secondOfficerDetailsThree = (By.XPATH, "(((//div[@class ='officers-details mb-4']/table/tbody)[1]/tr)[4]/td)[4]")
    qualificationOfOfficersSaveData = (By.XPATH, "(//span[contains(text(),'Save data')])[5]")
    chiefEngineerDetailsOne = (By.XPATH, "(((//div[@class ='officers-details mb-4'])[2]/table/tbody/tr)[2]/td)[2]")
    chiefEngineerDetailsTwo = (By.XPATH, "(((//div[@class ='officers-details mb-4'])[2]/table/tbody/tr)[2]/td)[3]")
    chiefEngineerDetailsThree = (By.XPATH, "(((//div[@class ='officers-details mb-4'])[2]/table/tbody/tr)[2]/td)[4]")
    secondEngineerDetailsOne = (By.XPATH, "(((//div[@class ='officers-details mb-4'])[2]/table/tbody/tr)[3]/td)[2]")
    secondEngineerDetailsTwo = (By.XPATH, "(((//div[@class ='officers-details mb-4'])[2]/table/tbody/tr)[3]/td)[3]")
    secondEngineerDetailsThree = (By.XPATH, "(((//div[@class ='officers-details mb-4'])[2]/table/tbody/tr)[3]/td)[4]")
    thirdEngineerDetailsOne = (By.XPATH, "(((//div[@class ='officers-details mb-4'])[2]/table/tbody/tr)[4]/td)[2]")
    thirdEngineerDetailsTwo = (By.XPATH, "(((//div[@class ='officers-details mb-4'])[2]/table/tbody/tr)[4]/td)[3]")
    thirdEngineerDetailsThree = (By.XPATH, "(((//div[@class ='officers-details mb-4'])[2]/table/tbody/tr)[4]/td)[4]")
    scrollToQuestionnaire = (By.XPATH, "//h4[contains(text(),'Questionnaire')]")
    certification = (By.XPATH, "(//summary[@class ='text_click'])[2]")
    certificationLevelOne = (By.XPATH, "(//details[@class ='sub_section']/summary)[1]")
    continuousSynopsisRecord = (By.XPATH, "(//details[@class ='question_position']/summary)[2]")
    browseImageClick = (By.XPATH, "//div/label[@class ='full-width full-height cursor-pointer']")
    defects = (By.XPATH, "//div[@name ='defects']")
    writeAnswer = (By.XPATH, "//textarea[@name ='answer_text']")
    saveAnswer = (By.XPATH, "//div[@class='save_button']//child::button//descendant::span[@class='vs-button-text vs-button--text']")
    next = (By.XPATH, "//button[@id ='next-question']")
    buttonToScroll = (By.XPATH, "//i[@class='vs-icon notranslate icon-scale vs-button--icon  feather icon-arrow-up null']")
    buttonToHomePage = (By.XPATH, "//i[@class ='vs-icon notranslate icon-scale vs-button--icon  feather icon-arrow-left null']")
    scrollToGeneralInformation = (By.XPATH, "//h4[contains(text(),'General Information')]")
    scrollToGeneralImage = (By.XPATH, "//h4[contains(text(),'General Images')]")
    scrollToQualificationOfOfficers = (By.XPATH, "//h4[contains(text(),'Qualification of Officers')]")

    def __init__(self, driver):
        self.driver = driver

    def inspectionPage(self, getData):
        self.sleep(15)
        self.scrollIntoView(self.driver.find_element(*InspectionPage.scrollToConsultantService))
        self.dropdownSelectByLi(getData["ConsultantService"], self.driver.find_element(*InspectionPage.service))
        self.sleep(20)

        self.elementClickByJS(self.driver.find_element(*InspectionPage.executiveSummaryClick))
        self.sleep(4)
        self.driver.switch_to.frame(self.driver.find_element(*InspectionPage.frameClick))
        self.clear(self.driver.find_element(*InspectionPage.clearExecutiveSummary))
        self.sendKeys(getData["ExecutiveSummary"], self.driver.find_element(*InspectionPage.clearExecutiveSummary))
        self.driver.switch_to.default_content()
        self.sleep(2)
        self.elementClickByJS(self.driver.find_element(*InspectionPage.executiveSummarySaveData))
        self.elementClickByJS(self.driver.find_element(*InspectionPage.vesselAssessmentClick))
        self.elementClickByJS(self.driver.find_element(*InspectionPage.selectVesselAssessment))
        self.elementClickByJS(self.driver.find_element(*InspectionPage.vesselAssessmentSaveData))
        self.scrollIntoView(self.driver.find_element(*InspectionPage.scrollToGeneralInformation))
        self.elementClickByJS(self.driver.find_element(*InspectionPage.generalInformationClick))
        self.sleep(7)
        self.elementHoverSend(getData["GeneralInformationOne"], self.driver.find_element(*InspectionPage.enterGeneralInformationOne))
        self.sleep(3)
        self.elementHoverSend(getData["GeneralInformationTwo"], self.driver.find_element(*InspectionPage.enterGeneralInformationTwo))
        self.sleep(2)
        self.elementClickByJS(self.driver.find_element(*InspectionPage.generalInformationSaveData))
        self.scrollIntoView(self.driver.find_element(*InspectionPage.scrollToGeneralImage))
        self.elementClickByJS(self.driver.find_element(*InspectionPage.generalImageClick))
        self.sleep(3)
        self.elementClick(self.driver.find_element(*InspectionPage.selectGeneralImage))

        self.sleep(2)
        self.elementClickByJS(self.driver.find_element(*InspectionPage.chooseFile))
        self.sleep(3)
        autoit.control_focus("Open", "Edit1")
        self.sleep(3)
        autoit.control_set_text("Open", "Edit1", "C:\\Users\\ALAGU SUNDARI\\PycharmProjects\\IQ-CRM_Admin\\TestData\\image4.png")
        self.sleep(3)
        autoit.control_click("Open", "Button1")
        self.sendKeys(getData["Description"], self.driver.find_element(*InspectionPage.description))
        self.dropdownSelectByLi(getData["Section"], self.driver.find_element(*InspectionPage.section))
        self.dropdownSelectByLi(getData["SubSection"], self.driver.find_element(*InspectionPage.subSection))
        self.sleep(3)
        self.elementClick(self.driver.find_element(*InspectionPage.generalImageSaveData))
        self.elementClick(self.driver.find_element(*InspectionPage.qualificationOfOfficersClick))
        self.sendKeys(getData["MasterDetailOne"], self.driver.find_element(*InspectionPage.masterDetailsOne))
        self.sendKeys(getData["MasterDetailTwo"], self.driver.find_element(*InspectionPage.masterDetailsTwo))
        self.sendKeys(getData["MasterDetailThree"], self.driver.find_element(*InspectionPage.masterDetailsThree))
        self.sendKeys(getData["ChiefOfficerDetailOne"], self.driver.find_element(*InspectionPage.chiefOfficerDetailsOne))
        self.sendKeys(getData["ChiefOfficerDetailTwo"], self.driver.find_element(*InspectionPage.chiefOfficerDetailsTwo))
        self.sendKeys(getData["ChiefOfficerDetailThree"], self.driver.find_element(*InspectionPage.chiefOfficerDetailsThree))
        self.sendKeys(getData["SecondOfficerDetailsOne"], self.driver.find_element(*InspectionPage.secondOfficerDetailsOne))
        self.sendKeys(getData["SecondOfficerDetailsTwo"], self.driver.find_element(*InspectionPage.secondOfficerDetailsTwo))
        self.sendKeys(getData["SecondOfficerDetailsThree"], self.driver.find_element(*InspectionPage.secondOfficerDetailsThree))
        self.sendKeys(getData["ChiefEngineerDetailOne"], self.driver.find_element(*InspectionPage.chiefEngineerDetailsOne))
        self.sendKeys(getData["ChiefEngineerDetailTwo"], self.driver.find_element(*InspectionPage.chiefEngineerDetailsTwo))
        self.sendKeys(getData["ChiefEngineerDetailThree"], self.driver.find_element(*InspectionPage.chiefEngineerDetailsThree))
        self.sendKeys(getData["SecondEngineerDetailOne"], self.driver.find_element(*InspectionPage.secondEngineerDetailsOne))
        self.sendKeys(getData["SecondEngineerDetailTwo"], self.driver.find_element(*InspectionPage.secondEngineerDetailsTwo))
        self.sendKeys(getData["SecondEngineerDetailThree"], self.driver.find_element(*InspectionPage.secondEngineerDetailsThree))
        self.sendKeys(getData["ThirdEngineerDetailOne"], self.driver.find_element(*InspectionPage.thirdEngineerDetailsOne))
        self.sendKeys(getData["ThirdEngineerDetailTwo"], self.driver.find_element(*InspectionPage.thirdEngineerDetailsTwo))
        self.sendKeys(getData["ThirdEngineerDetailThree"], self.driver.find_element(*InspectionPage.thirdEngineerDetailsThree))
        self.elementClickByJS(self.driver.find_element(*InspectionPage.qualificationOfOfficersSaveData))
        self.scrollIntoView(self.driver.find_element(*InspectionPage.scrollToQuestionnaire))
        self.elementClickByJS(self.driver.find_element(*InspectionPage.certification))
        self.elementClickByJS(self.driver.find_element(*InspectionPage.certificationLevelOne))
        self.sleep(3)
        self.elementClickByJS(self.driver.find_element(*InspectionPage.continuousSynopsisRecord))
        self.sleep(5)
        self.elementClick(self.driver.find_element(*InspectionPage.browseImageClick))
        self.sleep(3)
        autoit.control_focus("Open", "Edit1")
        self.sleep(3)
        autoit.control_set_text("Open", "Edit1", "C:\\Users\\ALAGU SUNDARI\\PycharmProjects\\IQ-CRM_Admin\\TestData\\download.jpeg")
        self.sleep(3)
        autoit.control_click("Open", "Button1")
        self.sleep(5)
        self.dropdownSelectByLi(getData["Defect"], self.driver.find_element(*InspectionPage.defects))
        self.sleep(5)
        self.sendKeys(getData["WriteAnswer"], self.driver.find_element(*InspectionPage.writeAnswer))
        self.sleep(5)
        self.elementClick(self.driver.find_element(*InspectionPage.saveAnswer))
        self.sleep(6)
        self.elementClickByJS(self.driver.find_element(*InspectionPage.buttonToScroll))
        self.sleep(6)
        self.elementClickByJS(self.driver.find_element(*InspectionPage.buttonToHomePage))

















